@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package crazypants.enderio.base.autosave.endercore;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;